# Generated by Django 4.2.18 on 2025-01-16 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='transaction_type',
        ),
    ]
