# Generated by Django 4.2.18 on 2025-01-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_remove_category_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='personal', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название статуса'),
        ),
    ]
